---
apiVersion: apps/v1
kind: DaemonSet
metadata:
   name: nginx-daemon
   labels:
      type: proxy
spec:
   selector:
     matchLabels:
        type: proxy
   template:
      metadata:
         name: nginx-pod
         labels:
            type: proxy
      spec:
         containers:
           - name: nginx-pod
             image: nginx
...
