---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: mysql-deployment
   labels: 
      type: db
      author: madhav
spec: 
   replicas: 2
   selector:
      matchLabels:
         type: db
   template:
     metadata:
        name: mysql-db
        labels:
          type: db
     spec:
       containers:
          - name: mysql
            image: mysql:5
            env:
              - name: MYSQL-ROOT-PASSWORD
                value: madhav
... 
