---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: nginx-deployment
   labels: 
    type: proxy
    author: madhav
spec:
   replicas: 2
   selector:
      matchLabels:
          type: proxy
   template: 
      metadata: 
         name: nginx-pod
         labels:
            type: proxy
      spec:
        containers:
          - name: my-nginx
            image: nginx
            ports: 
              - containerPort: 80
                hostPort: 80
...
