---
apiVersion: v1
kind: Pod
metadata:
   name: redis-pod
   labels:
      type: db
spec:
   containers:
      - name: redis-pod
        image: redis
        volumeMounts:
           - name: redis-volume
             mountPath: /data/reis
volumes:
   - name: redis-volume
     emptyDir: {}
...

