---
apiVersion: v1
kind: Pod
metadata: 
   name: httpd-pod
   labels:
      type: webserver
      author: madhav
spec:
   containers:
      - name: myhttpd
        image: httpd
        ports:
          - containerPort: 80
            hostPort: 80
...
