---
apiVersion: v1
kind: Pod
metadata: 
   name: gost-pod
   namespace: test-ns
   labels:
      type: cms
      author: madhav
spec:
   containers: 
      - name: gost
        image: ghost
        ports: 
          - containerPort: 2368
            hostPort: 8080
        env:
          - name: NODE_ENV
            value: development
...
