---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
   name: tomcat-rs
   labels:
      type: appserver
      author: madhav
spec:
  replicas: 4
  selector:
    matchLabels:
        type: appserver
  template:
     metadata:
        name: tomcat-pod
        labels: 
         type: appserver
     spec:
        containers:
           - name: mytomcat
             image: tomee
             ports: 
                - containerPort: 8080
                  hostPort: 8080
...
