---
apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
  labels:
    type: webserver
spec:
  containers:
    - name: myhttpd
      image: httpd
      resources:
           requests:
              memory: "64Mi"
              cpu: "250m"
           limits: 
              memory: "128Mi"
              cpu: "500m"
...                
