---
apiVersion: v1
kind: Service
metadata: 
   name: postgres-pod
   labels:
      type: db
      author: madhav
spec:
  type: ClusterIP
  ports:
   - targetPort: 5432
     port: 5432
  selector:
     type: db
     author: madhav
...
